name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: [self-hosted, mlu270-x5k]
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: >
          docker run --rm -v $(pwd):/work -w /work docker-user.extrotec.com:30080/cambricon/cnnl-ci:v0.3-ubuntu1604
          ./build.sh

      - name: test
        run: >
          docker run --rm --device /dev/cambricon_dev0 --device /dev/cambricon_ctl --device /dev/commu0
          -v $(pwd):/work -w /work/build/test -e LD_LIBRARY_PATH=/work/build/lib
          docker-user.extrotec.com:30080/cambricon/cnnl-ci:v0.3-ubuntu1604
          ./mluop_gtest
      - name: clean
        run: >
          docker run --rm -v $(pwd):/work -w /work docker-user.extrotec.com:30080/cambricon/cnnl-ci:v0.3-ubuntu1604
          rm -rf build
